language: node_js
sudo: false
node_js:
  - "8.11"
before_script: 
  - npm install --save-dev yarn
  - yarn add --dev jest

branches:
   only:
   - master

install:  
  - yarn install
 
script:
  - yarn test
